# Generated by Django 5.0.3 on 2024-12-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible_app', '0003_add_aramaic_source'),
        ('bible_app', '0003_alter_verse_translator'),
    ]

    operations = [
    ]
