# Generated by Django 5.1.2 on 2024-12-06 17:56

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('bible_app', '0006_add_processed_text_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='_processed_text',
        ),
        migrations.DeleteModel(
            name='AramaicWord',
        ),
        migrations.RemoveField(
            model_name='versetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='usernote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usernote',
            name='verse',
        ),
        migrations.AlterUniqueTogether(
            name='versetag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='versetag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='versetag',
            name='verse',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserNote',
        ),
        migrations.DeleteModel(
            name='VerseTag',
        ),
    ]